keys/src/address.rs, rpc/src/v1/impls/blockchain.rs, rpc/src/v1/impls/raw.rs, rpc/src/v1/types/address.rs, rpc/src/v1/types/mod.rs, rpc/src/v1/types/transaction.rs
This pr can be a prelude to simplifying rpc serialization.
It uses field attribute `#[serde(with = "module")]` ([docs](https://serde.rs/field-attrs.html)), but serialization can be also simplified using `#[serde(remote = "...")]` ([docs](https://github.com/serde-rs/serde/releases/tag/v1.0.0))
Please tell me what you think about it
=> keys::Address remote serialization

script/src/builder.rs
It would be very handy to have a builder for nulldata scripts, hence the nulldata builder. It is useful also to avoid having developers risk to make it in the wrong way.
The return_bytes function does not follow the rules for building op_return scripts, which are followed by is_nulldata. I've updated the function to make it compliant with what is_nulldata expect, with the minimum modifications required.
=> Add nulldata builder and fix op_return script push

README.md
I was trying to install this with a fresh Ubuntu 16.04 image and it kept failing on trying to install the `heapsize` dependency. Turned out I needed to install build-essentials with the cc and gcc compilers in order to build all of the dependencies. This was the only package I needed to install to successfully build `pbtc` in debug mode
=> Add build-essential install instructions to README

snap/snapcraft.yaml
This package will let you publish the latest parity-bitcoin in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.
=> Add the packaging metadata to build the parity-bitcoin snap

Cargo.lock, Cargo.toml, chain/Cargo.toml, chain/src/block.rs, chain/src/block_header.rs, chain/src/indexed_block.rs, chain/src/lib.rs, chain/src/transaction.rs, message/Cargo.toml, message/src/common/address.rs, message/src/common/block_header_and_ids.rs, message/src/common/block_transactions.rs, message/src/common/command.rs, message/src/common/service.rs, message/src/lib.rs, serialization_derive/Cargo.toml, serialization_derive/src/de.rs, serialization_derive/src/lib.rs, serialization_derive/src/ser.rs, serialization_derive/tests/raw.rs, tools/test.sh
I was a bit annoyed with the amount of boilerplate we are writing for serialization so I implemented `serialization_derive` here as a poc. If this pr gets accepted, I will do the same for parity's rlp serialization.
=> custom serialization preprocessor macro

Cargo.lock, chain/Cargo.toml, db/src/block_chain_db.rs, miner/Cargo.toml, miner/src/block_assembler.rs, miner/src/cpu_miner.rs, p2p/src/io/deadline.rs, primitives/Cargo.toml, rpc/src/lib.rs, rpc/src/v1/impls/blockchain.rs, rpc/src/v1/impls/network.rs, rpc/src/v1/impls/raw.rs, script/src/lib.rs
1) I have noticed that with rust 1.19 && nightly our tests are failing with `SIGSEGV` => updated `heapsize` (and all others, by the way) dependency
2) `jsonrpc` updated => fixed work with `Trailing` struct
3) fixed all compilation warnings
=> Update dependencies && and fix warnings

README.md
Putting the installation instructions for the snap will help getting more testers, and then to publish it in the stable channel with more confidence.
=> Add the command to install the parity-bitcoin snap

message/src/types/version.rs, p2p/src/net/connections.rs, p2p/src/p2p.rs, p2p/src/protocol/sync.rs, p2p/src/util/peer.rs, sync/src/inbound_connection.rs, sync/src/local_node.rs, sync/src/synchronization_chain.rs, sync/src/synchronization_client_core.rs, sync/src/synchronization_manager.rs, sync/src/synchronization_peers_tasks.rs
closes #399 
closes #375 
closes (partially) #298
1) until now, if peer had many sync failures, it was 'excluded' from synchronization, but still occupied connection slot. Now if it has enough failures, connection is closed + peer is penalized on p2p level (i.e. in NodeTable) to not to reconnect to the same peer right after dropping connection. Without it, pbtc won't survive in post-HF network - it could stay connected to peers from 'other' network forever
2) added stub for dynamic calculation (`BlocksRequestLimits` + `TrustLevel`) of min/max blocks in getdata requests. Large min/max are useful at the beginning of blockchain, when blocks are small. Small are useful after block size increases. Currently I haven't found good equation to calculate this (experimented earlier this week) - so …
=> Synchronization fixes

db/src/block_chain.rs, db/src/block_chain_db.rs, pbtc/cli.yml, pbtc/commands/mod.rs, pbtc/commands/rollback.rs, pbtc/main.rs
closes #437
Example:
```
svyatonik@xwnotebook:~/dev/parity-bitcoin.test$ ./pbtc --db-cache=2048 -d ./db.test 2>&1 rollback 1000
Block Number(1000) is unknown
svyatonik@xwnotebook:~/dev/parity-bitcoin.test$ RUST_LOG=sync=info ./pbtc --db-cache=2048 -d ./db.test 2>&1 | tee start_trace.log
INFO:sync::synchronization_client_core: Processed 1000 blocks in 1.04 seconds (965.40 blk/s).	Peers: 9 (act: 9, idl: 0, bad: 4).	Chain: [sch:4336 -> req:517 -> vfy:147 -> stored: 1001]
INFO:sync::synchronization_client_core: Processed 1000 blocks in 0.58 seconds (1713.47 blk/s).	Peers: 10 (act: 10, idl: 0, bad: 2).	Chain: [sch:3184 -> req:797 -> vfy:19 -> stored: 2001]
INFO:sync::synchronization_client_core: Processed 1000 blocks in 0.88 seconds (1137.90 blk/s).	Peers: 10 (act: 10, idl: 0, bad: 2).	Chain: …
```
=> `rollback` command implemented

db/src/block_ancestors.rs, verification/src/accept_header.rs, verification/src/deployments.rs
+ fixed deployments calculation
It is a part of #443 fix - I'll return `expect()` call after synchronizing testnet
=> Added deployments tests from bitcoin

sync/src/synchronization_chain.rs, verification/src/deployments.rs
on top of #451 
Fixed insertion to `DeploymentStateCache`, so that it has correct entry after first insertion in edge cases.
Added test to ensure that cache works as intended.
Added separate `DeploymentStateCache` in sync Chain. It could be the same as in `ChainVerifier` right now, but when implemented properly (it is not critical, though), it must depend on known headers, instead of stored blocks (like cache in `ChainVerifier` does).
=> Deployments state cache fix

README.md, logs/src/lib.rs, pbtc/cli.yml, pbtc/config.rs, pbtc/main.rs
Incldues:
- Default to default logging `sync=info`.
- Introduce `--quiet` flag to suppress that.
- Improve help messages wording a little bit.
- Updated README.md to reflect the changes.
Rationale:
- It certainly makes sense to default to `sync=info` logging at some point. (Or to write a beautiful logger.)
- Downside is that any use of `RUST_LOG` only works in combination with the `-q` switch to suppress the default logging.
=> Default to default logging sync=info

README.md, db/src/block_chain_db.rs, db/src/error.rs, db/src/kv/memorydb.rs, db/src/kv/transaction.rs, db/src/lib.rs, db/src/store.rs, pbtc/cli.yml, pbtc/commands/import.rs, pbtc/commands/rollback.rs, pbtc/commands/start.rs, pbtc/config.rs, pbtc/util.rs, tools/regtests.sh
So from now users without database or with empty database or with old version of database will receive message => "You must select fork on first run: --segwit, --segwit2x, --bitcoin-cash".
After selecting fork, it can't be changed anymore. Trying to switch to another fork will lead to "Cannot select 'segwit2x' fork with non-empty database of 'segwit' fork"-like error.
After first run, fork is read from database => passing flag is not required anymore.
Example:
```
svyatonik@xwnotebook:~/dev/parity-bitcoin.test$ rm -rf db.test
svyatonik@xwnotebook:~/dev/parity-bitcoin.test$ ./pbtc -d db.test
You must select fork on first run: --segwit, --segwit2x, --bitcoin-cash
svyatonik@xwnotebook:~/dev/parity-bitcoin.test$ ./pbtc -d db.test --segwit
2017-09-01 17:13:14  INFO sync Processed 1000 blocks …
```
=> Force user to select chain on first run

docker/hub/Dockerfile, docker/ubuntu/Dockerfile
Fixes: #409
There are already Dockerfiles present, but this PR updates them to,
- Use a [multi-stage build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) to improve image size and remove unnecessary packages after build
- Use Ubuntu 16.04 instead of 14.04 for the runtime image
Tested both hub and non-hub builds and `pbtc` binary runs successfully from runtime container.
=> Update Dockerfiles to multi-stage and Ubuntu 16.04

network/src/consensus.rs
It wasn't mentioned in https://segwit2x.github.io/segwit2x-announce.html , so I missed it. Have found it today in https://github.com/btc1/bitcoin/commit/b368c9bfbbea8161a719ac6fda89bcb9909ea83e . Will double check this branch later (in next few days, after dealing with other urgent issues).
=> Added Segwit2x rollback protection

p2p/src/io/deadline.rs, p2p/src/p2p.rs, sync/src/local_node.rs, sync/src/types.rs
closes #473 
Was working on some `pbtc` changes && found that some actual warnings are hidden behind these.
Fixed it with a bruteforce - just added `Box::new()` where required.
=> Fixed BoxFuture-related warnings

README.md, network/src/consensus.rs, network/src/lib.rs, pbtc/cli.yml, pbtc/config.rs, pbtc/seednodes.rs, verification/src/accept_block.rs, verification/src/accept_transaction.rs
Since there are now 2 **different** forks named 'Segwit2x':
https://segwit2x.github.io/ - increasing max block size to 2MB
http://b2x-segwit.io - increasing block size, difficulty adjustment, premine, different hashing algorithm, ...
And the origin (1st one) fork has failed => let's remove all mentions for not to confuse users.
=> Remove segwit2x mentions

README.md, docker/hub/Dockerfile, docker/ubuntu/Dockerfile, message/src/common/command.rs
Found warning in https://travis-ci.org/paritytech/parity-bitcoin/builds/339518985 . Reason: https://github.com/rust-lang/rust/pull/44042 . So there are two options to fix this warning - either to add `#[allow(unused_imports)]`, or to bump up minimal required `rustc` version. I prefer to require 1.23. If you know any problems with this - please speak now or forever hold your peace :)
=> Removed AsciiExt import

primitives/src/bytes.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/opcode.rs, script/src/script.rs, script/src/stack.rs
on top of #486 (i.e. this PR is for commits: https://github.com/paritytech/parity-bitcoin/pull/487/commits/34239d4fbe2a18c127d98d926d2cbb1d6963bafd + https://github.com/paritytech/parity-bitcoin/pull/487/commits/7beffdfdc982b3ca41f6b91817385b036ef2d5a8)
part of #479 
According to [OP_CAT](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_cat) specification
This PR won't affect consensus, until [May 2018 Hardfork transition](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-hardfork.md#summary) will be implemented
=> Bitcoin Cash: OP_CAT implementation

primitives/src/bytes.rs, script/src/error.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/num.rs, script/src/opcode.rs
on top of #489 (i.e. this PR is for commit: https://github.com/paritytech/parity-bitcoin/commit/06a4ef8dbc409f434796c9a68d6430f56fd22488)
part of #479 
According to [OP_DIV](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_div) and [OP_MOD](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_mod) specification
This PR won't affect consensus, until [May 2018 Hardfork transition](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-hardfork.md#summary) will be implemented
=> Bitcoin Cash: OP_DIV and OP_MOD implementation

primitives/src/bytes.rs, script/src/error.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/opcode.rs, script/src/script.rs, script/src/stack.rs
on top of #488 (i.e. this PR is for commit: https://github.com/paritytech/parity-bitcoin/commit/aca8deeeba642558268cfe01bc94944997c63231)
part of #479 
According to [OP_AND](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_and), [OP_OR](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_or), [OP_XOR](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_xor) specification
This PR won't affect consensus, until [May 2018 Hardfork transition](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-hardfork.md#summary) will be implemented
=> Bitcoin Cash: OP_AND, OP_OR, OP_XOR implementation

README.md, bencher/src/verifier.rs, message/src/message/message_header.rs, network/src/consensus.rs, network/src/network.rs, p2p/src/io/handshake.rs, p2p/src/io/read_any_message.rs, p2p/src/io/read_header.rs, p2p/src/io/read_message.rs, pbtc/cli.yml, pbtc/config.rs, sync/src/blocks_writer.rs, sync/src/local_node.rs, sync/src/synchronization_chain.rs, sync/src/synchronization_client_core.rs, sync/src/synchronization_verifier.rs, tools/regtests.sh, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/work_bch.rs
TL;DR clean up with some historical terms like Segwit versus UAHF:
--bch             Use Bitcoin Cash verification rules (BCH).
--btc             Use Bitcoin Core verification rules (BTC).
Also renamed `ConsensusFork::NoFork to ::BitcoinCore`, I was a bit pedantic about that :-p
=> Distinguish BTC and BCH

Cargo.lock, Cargo.toml
This PR fix compiling on macOS. Currently with `app_dirs 1.1.1` on macOS:
```
error[E0282]: type annotations needed
--> /Users/i1skn/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
|
10 |         Ok(Component::RootDir.as_ref().into())
|                                        ^^^^ cannot infer type for `T`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0282`.
error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Fix for the same issue in `parity` - https://github.com/paritytech/parity/pull/8268
=> Update app_dirs to 1.2.1

network/src/consensus.rs, sync/src/local_node.rs, verification/src/accept_block.rs, verification/src/accept_chain.rs, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/lib.rs, verification/src/work_bch.rs
closes #479 
This [commit](https://github.com/paritytech/parity-bitcoin/commit/70b08a7ca007d496e606a163422e3e5772d63695) may be reverted later, replacing `monolith_time` with `monolith_height` for both performance + code clarity.
=> Bitcoin Cash: monolith activation

pbtc/seednodes.rs
Current seed nodes are outdated which results in the IBD for Bitcoin Cash
(mainnet & testnet) never starting. The newly introduced nodes fix this
problem.
=> Update bitcoin cash seed nodes from bitcoin-abc

Cargo.toml
Cargo warns about it being unused.
=> Remove `doc` profile from Cargo.toml.

message/src/common/inventory.rs, network/src/consensus.rs, sync/src/lib.rs, sync/src/synchronization_chain.rs, sync/src/synchronization_client_core.rs
closes #537 
The issue is that post-SegWit activation blocks were requested **before** SegWit activation block is inserted + canonized => they were requested without witness data => verification has failed && they were marked as dead-end blocks. Since we never clear dead-end blocks, the node was unable to recover.
Solution: always ask for witness in blocks/transactions requests on the `--btc` chain (witness is simply not returned before `SegWit` is activated)
=> Always ask for witness when requesting b/tx on --btc chain

miner/src/block_assembler.rs, network/src/consensus.rs, network/src/lib.rs, verification/src/accept_block.rs, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/duplex_store.rs, verification/src/error.rs, verification/src/work_bch.rs
part of #519 
This PR introduces:
1) Nov 2018 HF MTP
2) enforces canonical ordering for all post-HF blocks
=> BCH Nov2018 HF: canonical transaction ordering

miner/src/block_assembler.rs, network/src/consensus.rs, network/src/lib.rs, script/src/error.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/opcode.rs, script/src/script.rs, script/src/verify.rs, sync/src/local_node.rs, verification/src/accept_block.rs, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/duplex_store.rs, verification/src/error.rs, verification/src/sigops.rs, verification/src/verify_block.rs, verification/src/verify_transaction.rs, verification/src/work_bch.rs
on top of #524 
these commits only: https://github.com/paritytech/parity-bitcoin/commit/ad4f51ac07369c6b0659c1f60d8dd5e5b129ae48 + https://github.com/paritytech/parity-bitcoin/pull/525/commits/cc823839a6228eef63efe0b2b259b7f4ea12e0a6
part of #519 
This PR introduces two new opcodes (`OP_CHECKDATASIG` + `OP_CHECKDATASIGVERIFY`) that are enabled in post-HF BCH scripts.
=> BCH Nov2018 HF: OP_CHECKDATASIG + OP_CHECKDATASIGVERIFY

miner/src/block_assembler.rs, network/src/consensus.rs, network/src/lib.rs, script/src/error.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/opcode.rs, script/src/script.rs, script/src/verify.rs, sync/src/local_node.rs, verification/src/accept_block.rs, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/duplex_store.rs, verification/src/error.rs, verification/src/sigops.rs, verification/src/verify_block.rs, verification/src/verify_transaction.rs, verification/src/work_bch.rs
on top of #525 
these commits only: https://github.com/paritytech/parity-bitcoin/commit/ad4f51ac07369c6b0659c1f60d8dd5e5b129ae48 + https://github.com/paritytech/parity-bitcoin/pull/526/commits/18a2766fb9e535686dbfb117a17982dbe51844a2
part of #519 
This PR introduces new consensus rule - all post-HF transactions must be > than 100 bytes.
P.S. we should have some kind of trigger which is fired when HF block appears + clears the memory pool. Otherwise memory pool could contain invalid transactions. (submitted an issue #527)
=> BCH Nov2018 HF: min tx size is 100 bytes

miner/src/block_assembler.rs, network/src/consensus.rs, network/src/lib.rs, script/src/error.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/opcode.rs, script/src/script.rs, script/src/verify.rs, sync/src/local_node.rs, verification/src/accept_block.rs, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/duplex_store.rs, verification/src/error.rs, verification/src/sigops.rs, verification/src/verify_block.rs, verification/src/verify_transaction.rs, verification/src/work_bch.rs
on top of #526 
this commit only: https://github.com/paritytech/parity-bitcoin/commit/edfb92cde3f73eb24b8ace4d4f9d10ed0e6c89ce
part of #519 
This PR disables all non-push operations in scriptSig-s.
=> BCH Nov2018 HF: enforce push-only restriction for scriptsig

miner/src/block_assembler.rs, network/src/consensus.rs, network/src/lib.rs, script/src/error.rs, script/src/flags.rs, script/src/interpreter.rs, script/src/opcode.rs, script/src/script.rs, script/src/verify.rs, sync/src/local_node.rs, verification/src/accept_block.rs, verification/src/accept_transaction.rs, verification/src/chain_verifier.rs, verification/src/duplex_store.rs, verification/src/error.rs, verification/src/sigops.rs, verification/src/verify_block.rs, verification/src/verify_transaction.rs, verification/src/work_bch.rs
on top of #528  
this commit only: https://github.com/paritytech/parity-bitcoin/commit/d96be02e5680cf3c4a590659abf235d2bd3ebb4c
part of #519 
This PR enforces post-HF clean-stack check (single non-zero item must be in the stack after successful script eval).
=> BCH Nov2018 HF: enforce clean-stack restriction for scripts

rpc/src/v1/impls/raw.rs
Fixes a compiler warning that these are redundant.
=> chore: remove redundant imports

Cargo.lock, keys/Cargo.toml, network/Cargo.toml
This is to fix compiler warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
=> chore: upgrade lazy_static dependency

README.md
`--skip-verification` flag seems to be quiet outdated
=> Fixed CLI for no-verification import
