paritytech/parity-bitcoin

Cargo.lock
chain/Cargo.toml
db/src/block_chain_db.rs
message/src/types/version.rs
miner/Cargo.toml
miner/src/block_assembler.rs
miner/src/cpu_miner.rs
p2p/src/io/deadline.rs
p2p/src/io/handshake.rs
primitives/Cargo.toml
rpc/src/lib.rs
rpc/src/v1/impls/blockchain.rs
rpc/src/v1/impls/network.rs
rpc/src/v1/impls/raw.rs
script/src/lib.rs

closes #48 
on top of #429 (this PR is for https://github.com/paritytech/parity-bitcoin/commit/8ce87528ec4d689f6b99829fa0531a78cbd18b4f only)

Verify nonce from version message

---

p2p/src/io/handshake.rs

I'm playing with sync code these days && have noticed that ~50% of nodes are ignoring all our requests =>  sync queue is not fulfilled normally. The common thing that all these nodes are Satoshi/0.14+. And then I have found this:
https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L1436
After this PR everything looks fine.

Send verack during handshake

---

logs/src/lib.rs
sync/src/synchronization_client_core.rs
sync/src/synchronization_manager.rs
sync/src/synchronization_peers.rs
sync/src/synchronization_peers_tasks.rs

What's in there:
- enhanced logger, colored based on log level
- reformatted sync info, added performance indicator (blk/s)
- reworded some warnings
Rationale:
- this is my first rust contribution, review with ultra caution :p
- colored logs might require a --no-color switch in future

Improved logging to console

---

sync/src/utils/orphan_transactions_pool.rs

Fix panic in orphan transaction pool

---

.gitlab-ci.yml
.travis.yml

Fix typo in CI scripts

---

README.md
pbtc/cli.yml
rpc/src/v1/traits/blockchain.rs
rpc/src/v1/traits/miner.rs
rpc/src/v1/traits/network.rs
rpc/src/v1/traits/raw.rs

what:
- fixed some typos
- improved cli help
- added jsonrpc examples to readme
rationale:
- should be automated at some point
- should probably go into a dedicated wiki page as soon as there are more apis.

Add basic documentation for available JSONRPC APIs.

---

logs/src/lib.rs
network/src/consensus.rs
p2p/src/io/handshake.rs
pbtc/config.rs
sync/src/synchronization_client_core.rs
verification/src/accept_transaction.rs
verification/src/work_bch.rs

...this improves initial sync performance

Bitcoin Cash: hardcode DAA HF height

---

script/src/interpreter.rs
script/src/script.rs
script/src/stack.rs

preliminary for #479 (do not want to use `try!` or mix styles)

Replace try! with ? in script

---

primitives/src/bytes.rs
script/src/error.rs
script/src/flags.rs
script/src/interpreter.rs
script/src/opcode.rs
script/src/script.rs
script/src/stack.rs

on top of #487 (i.e. this PR is for commit: https://github.com/paritytech/parity-bitcoin/commit/05f885bfd95519881d0483a6c472a17fb361823b)
part of #479 
According to [OP_SPLIT](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-reenabled-opcodes.md#op_split) specification
This PR won't affect consensus, until [May 2018 Hardfork transition](https://github.com/schancel/spec/blob/5e9319028e85321c24eac9fe4b47e60c42b315bc/may-2018-hardfork.md#summary) will be implemented

Bitcoin Cash: OP_SPLIT implementation

---

Cargo.lock
script/src/error.rs
script/src/flags.rs
script/src/interpreter.rs
script/src/opcode.rs
storage/Cargo.toml
storage/src/lib.rs

also some small renamings + removed unused crate (fixed warning)

Bitcoin Cash: OP_NUM2BIN implementation

---

script/src/script.rs

Fix witness commitment size check

---

Cargo.lock
keys/Cargo.toml
network/Cargo.toml
verification/Cargo.toml

Update lazy_static dependencies to 1.0

---

chain/README.md

Hello!
Over the past couple months I have embarked on an exciting journey to learn the rust programming language. In search of an interesting project to experiment with (and maybe even one day contribute to) I discovered this Bitcoin client. As I began to simultaneously read through the codebase and reread *Mastering Bitcoin* I began taking notes to help myself build a basic understanding of how all this stuff works. This evolved into a few crate level README's, such as this one.
I am opening this PR in hopes of creating documentation that may help future rust Bitcoin devs.

Add Chain Crate README

---

pbtc/cli.yml
pbtc/commands/start.rs
pbtc/config.rs

I think I resolved #495, I would appreciate any comment or advice.
I was also wondering if it would be better to use something like "listen_host" and "listen_port", or "bind_host", in order to prevent any confusion.
Any thought on this?

Listening address is hardcoded to 127 0 0 1 #495

---

rpc/src/v1/types/transaction.rs

https://github.com/paritytech/jsonrpc/commit/59cb86b7bd90aa55bb571df692a800b44463b0e9

Fix Params deserialization on serde_json>=1.0.8

---

pbtc/config.rs

Fix panic when started for the first time without selecting a fork

---

.gitlab-ci.yml
logs/src/lib.rs
network/src/network.rs
sync/src/utils/bloom_filter.rs

backport of https://github.com/paritytech/parity-zcash/pull/52

Fixed script iteration in bloom filter

---

miner/src/memory_pool.rs
sync/src/lib.rs

Allow zero fee transactions on regtest network

---

docker/ubuntu/Dockerfile

RUST -> 1.34
UBUNTU -> Bionic
Close https://github.com/paritytech/parity-bitcoin/issues/541

update Ubuntu Dockerfile

---

script/src/interpreter.rs

Use empty value as false in comparison ops

---

.gitlab-ci.yml
tools/regtests.sh

Run regtests on CI

---

Cargo.lock
rpc/src/v1/impls/raw.rs
rpc/src/v1/types/transaction.rs

Partially #247 #308 
- Implemented `decoderawtransaction`.
- Add test for getrawtransaction(verbose=true) https://github.com/paritytech/parity-bitcoin/pull/551#pullrequestreview-223828261

Raw JSON RPC `decoderawtransaction`

---

Cargo.lock

[fix build]: bump `getopts` 

---

sync/src/synchronization_chain.rs

Now only the hashes being removed are copied, rather than all of them in verifying_transactions.

fix: copy less hashes when removing invalid txs during sync
